# Generated by Django 3.0.6 on 2020-05-28 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benpelumiscrumy', '0003_auto_20200513_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrumy_goal', to='benpelumiscrumy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='owner',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrumy_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_from',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='moved_to',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='scrumyhistory',
            name='time_of_action',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
